### ISSUE TITLE
possibly invalid geonames term id used: GEONAMES:9062339

### ISSUE THREAD

**Issue by jhpoelen** [millerse/Lice#1]
I noticed a warning from import logs - it seems that a geonames id is used that does not or not longer exists. (see attached screenshot).

```
02:21:35,864  WARN GeoNamesServiceImpl:265 - failed to locate (lat,lng) for term [GEONAMES:9062339]
```

![screenshot from 2017-10-11 07-40-44](https://user-images.githubusercontent.com/1084872/31447816-b67238b4-ae57-11e7-9491-3ac4ee96fced.png)

**Comment by millerse** [comment]
Fixed

**Comment by jhpoelen** [comment]
Wow! that was fast . . . what was the issue? Also, I am assuming that you'll make a new release and add to Zenodo community so that GloBI get use the latest and greatest from Zenodo.
